name: product_app
description: A Flutter app for product test
publish_to: 'none' # Remove this line if publishing to pub.dev

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  intl: ^0.17.0
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
